[package]
name = "sites_integrity"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
hdi.workspace = true
serde.workspace = true
holochain_serialized_bytes.workspace = true

[features]
default = []
integrity = []
